# Generated by Django 5.2 on 2025-04-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='correo',
            field=models.EmailField(default='vsalazars@sesna.gob.mx', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('OIC', 'Órgano Interno de Control'), ('FISCALIA', 'Fiscalía'), ('AUTORIDAD_INVESTIGADORA', 'Autoridad Investigadora'), ('DENUNCIANTE', 'Denunciante')], default='ADMIN', max_length=50),
            preserve_default=False,
        ),
    ]
