# Generated by Django 5.2 on 2025-04-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0004_customuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.AddField(
            model_name='customuser',
            name='correo_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(max_length=30),
        ),
    ]
