# Generated by Django 5.2 on 2025-04-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0005_remove_customuser_email_customuser_correo_enviado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='estado',
            field=models.CharField(blank=True, choices=[('CDMX', 'Ciudad de México'), ('JAL', 'Jalisco'), ('NL', 'Nuevo León'), ('MEX', 'Estado de México')], max_length=50, null=True),
        ),
    ]
