# Generated by Django 5.2 on 2025-04-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0006_customuser_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoDenuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('EN_ANALISIS', 'En análisis por OIC'), ('TURNADA_AUTORIDAD', 'Turnada a Autoridad Investigadora (falta grave)'), ('TURNADA_FISCALIA', 'Turnada a Fiscalía Anticorrupción (corrupción)'), ('RECHAZADA', 'Rechazada por falta de elementos'), ('CONCLUIDA', 'Concluida con resolución del OIC (no grave)')], default='EN_ANALISIS', max_length=40)),
                ('fecha_turno', models.DateField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='estado',
            field=models.CharField(blank=True, choices=[('AGS', 'Aguascalientes'), ('BC', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAMP', 'Campeche'), ('CDMX', 'Ciudad de México'), ('CHIS', 'Chiapas'), ('CHIH', 'Chihuahua'), ('COAH', 'Coahuila'), ('COL', 'Colima'), ('DGO', 'Durango'), ('GTO', 'Guanajuato'), ('GRO', 'Guerrero'), ('HGO', 'Hidalgo'), ('JAL', 'Jalisco'), ('MEX', 'Estado de México'), ('MICH', 'Michoacán'), ('MOR', 'Morelos'), ('NAY', 'Nayarit'), ('NL', 'Nuevo León'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QRO', 'Querétaro'), ('QROO', 'Quintana Roo'), ('SLP', 'San Luis Potosí'), ('SIN', 'Sinaloa'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAMPS', 'Tamaulipas'), ('TLAX', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucatán'), ('ZAC', 'Zacatecas')], max_length=50, null=True),
        ),
    ]
