# Generated by Django 5.2 on 2025-04-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0007_seguimientodenuncia_alter_customuser_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientodenuncia',
            name='fecha_turno',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
