# Generated by Django 5.2 on 2025-04-18 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0008_alter_seguimientodenuncia_fecha_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientodenuncia',
            name='fecha_turno',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
