# Generated by Django 5.2 on 2025-04-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0009_alter_seguimientodenuncia_fecha_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientodenuncia',
            name='folio',
            field=models.CharField(max_length=100),
        ),
    ]
